### ISSUE TITLE
MGB Contrast Wheel

### ISSUE THREAD

**Issue by George304** [Gekkio/gb-schematics#3]
Gekkio,

I was checking your schematic for the MGB. I’m new to this so I don’t understand that much. I have an MGB and the contrast wheel doesn’t work. It was working before but not anymore. I need your help trying to diagnose what could it be. I change the contrast wheel with a new one but the issue persist.

Respectfully,

George

**Comment by Gekkio** [comment]
Hello,

This is not really the best place to ask for repair/modding/diagnostics help. I recommend the [/r/gameboy reddit](https://www.reddit.com/r/Gameboy/), or even better, its Discord server (https://discord.gg/gameboy). There are many knowledgeable people there (including me), and it's much easier to have a discussion there instead of here in a random Github issue very few people will read :slightly_smiling_face:
